from typing import Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from trading_bot.types import Book, Fill
    from trading_bot.strategy.api import StrategyAPI


class Strategy(Protocol):
    name: str
    coin: str
    errored: bool

    def on_init(self, api: "StrategyAPI") -> None: ...
    def on_tick(self, coin: str, mid_price: float) -> None: ...
    def on_fill(self, fill: "Fill") -> None: ...
    def on_timer(self) -> None: ...
    def on_book(self, book: "Book") -> None: ...
    def on_shutdown(self) -> None: ...
